const START_FETCH_SEASONS_LIST = 'season/START_FETCH_SEASONS';
const END_FETCH_SEASONS_LIST = 'season/END_FETCH_SEASONS';
const FETCH_SEASONS_LIST_ERROR = 'season/FETCH_SEASONS_LIST_ERROR';

const START_FETCH_SEASON_RESULT = 'season/BEGIN_FETCH_SEASON_RESULT';
const END_FETCH_SEASON_RESULT = 'season/END_FETCH_SEASON_RESULT';
const FETCH_SEASON_RESULT_ERROR = 'season/FETCH_SEASON_RESULT_ERROR';

export default {
    START_FETCH_SEASONS_LIST,
    END_FETCH_SEASONS_LIST,
    START_FETCH_SEASON_RESULT,
    END_FETCH_SEASON_RESULT,
    FETCH_SEASON_RESULT_ERROR,
    FETCH_SEASONS_LIST_ERROR
};
